### ISSUE TITLE
Problem with Creating App

### ISSUE THREAD

**Issue by fmanshaii** [simonbs/SBSAnimoji#10]
May you please show me how to download this app. I made a developer account. What are the steps to compile the app and how can I put it on my iPhone X.

**Comment by simonbs** [comment]
Yoy may find the following guides helpful.
1. [Cloning a repository](https://help.github.com/articles/cloning-a-repository/)
2. [Launching Your App on Devices](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html)
