### ISSUE TITLE
AvatarKit.framework not loaded

### ISSUE THREAD

**Issue by irshadpc** [simonbs/SBSAnimoji#12]
dyld: Library not loaded: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
  Referenced from: /var/containers/Bundle/Application/A5437001-83D4-4E36-871C-66621293C645/SBSAnimoji.app/SBSAnimoji
The abocve issues when i faced to run the application. Any suggestions?

**Comment by simonbs** [comment]
Make sure:
1) You are running on the device, not the simulator.
2) The device you are running the app on is an iPhone X.

Is this the case?

**Comment by irshadpc** [comment]
@simonbs I have run on iPhone 7.
 Is AvatarKit.framework only available on iPhone X?

**Comment by simonbs** [comment]
@irshadpc Correct. AvatarKit is only available on iPhone X.
