### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by chance-RCS** [simonbs/SBSAnimoji#15]
When I'm trying to build and run onto my iPhone, xCode is aborting the build.

Error Message is:
dyld: Library not loaded: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
  Referenced from: /var/containers/Bundle/Application/F6441407-982B-4614-941B-F9D1602D9E44/SBSAnimoji.app/SBSAnimoji
  Reason: image not found
(lldb) 

Any ideas?

**Comment by simonbs** [comment]
@chance-allred It looks like you are not trying to run on an iPhone X. Is this correct? Apples AvatarKit, which this project depends on, is only available on iPhone X.

**Comment by chance-RCS** [comment]
@simonbs Thanks for the quick response! That seems to be the issue :(. Looks like I'll have to wait till my iPhone X ships!

Thanks for the help!
