### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by zabikk** [simonbs/SBSAnimoji#16]
Im getting error 
/Users/zabik/Desktop/SBSAnimoji-master/SBSAnimoji/Pages/Main/MainView.m:96:61: Property 'safeAreaLayoutGuide' not found on object of type 'MainView *'

**Comment by liangxingyan** [comment]
I'm build error

**Comment by simonbs** [comment]
Please make sure that you are running the app on an i iPhone X. Is this the case?

**Comment by zabikk** [comment]
Yea I had tried to run it on a iPhone X

**Comment by zabikk** [comment]
Update there was another part of Xcode that was not loading properly and that was causing the issues I closed and relaunched Xcode and we were fine.
