### ISSUE TITLE
Error code signing AvatarKit framework

### ISSUE THREAD

**Issue by sabrinacharania** [simonbs/SBSAnimoji#18]
I have signed in with my developer account and keep receiving an error during Code signing and build fails. Any suggestions?

**Comment by joeycortez42** [comment]
Did you trust the developer profile on your phone? General -> Device Management

**Comment by simonbs** [comment]
Make sure that you have followed [Apples guide](https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/LaunchingYourApponDevices/LaunchingYourApponDevices.html) on running an app on your device.
