### ISSUE TITLE
Can't load AvatarKit framework 

### ISSUE THREAD

**Issue by dingtianran** [simonbs/SBSAnimoji#20]
Running on Xcode, get"
dyld: Library not loaded: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
  Referenced from: /var/containers/Bundle/Application/DA6405E7-90F4-4857-8995-DDD25EAD020A/SBSAnimoji.app/SBSAnimoji
  Reason: image not found
Message from debugger: Terminated due to signal 6"

Not sure what happened, is there some thing missing?

**Comment by simonbs** [comment]
It sounds like you are not running this on an iPhone X. Only the iPhone X is supported.
