### ISSUE TITLE
iOs Beta Versions

### ISSUE THREAD

**Issue by StoneyP** [simonbs/SBSAnimoji#21]
Hello and thank you for such an amazing and necessary compliment to a sweet new feature :-) 

I am trying to load the app from xcode Beta version 9.2 while running iOs 11.2 Beta 4 on my iPhone X. . . I am receiving this message: 
** iOS Deployment Target '11.2' is newer than SDK 'iOS 11.1' in target SBSAnimoji / Code will load on this and later versions of iOS. Framework APIs that are unavailable in earlier versions will be weak-linked; your code should check for null function pointers or specific system versions before calling newer APIs**

Please advise with any and all help you are able to provide with this issue. Thank you.

**Comment by DrJapan** [comment]
There are two things you need change  to make this work with the new iOS betas:

1. Under the project settings, Deployment Target, you need to update it to 11.2
2. Under the Targets, SBSAnimoji, Deployment Target, update that one to 11.2

Re-run/build on your device, and you'll be back to working.

![screen shot 2017-11-20 at 12 43 21 am](https://user-images.githubusercontent.com/8658896/33005559-f48b7568-cd8b-11e7-9501-7d33dc6969cf.png)

**Comment by AnGen** [comment]
Is it possible compile and run on iphone 8?

**Comment by simonbs** [comment]
@AnGen No.
