### ISSUE TITLE
Couldnt run the project. I am getting following error.

### ISSUE THREAD

**Issue by RagulChandra** [simonbs/SBSAnimoji#22]
Apple Mach-O Linker Error Group
  "_OBJC_METACLASS_$_AVTPuppetView", referenced from:

  "_OBJC_CLASS_$_AVTPuppetView", referenced from:

  "_OBJC_CLASS_$_AVTPuppet", referenced from:

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by alkalinecoffee** [comment]
Is the target set to your connected iPhone?
