### ISSUE TITLE
Noob issue building the app

### ISSUE THREAD

**Issue by Archundix** [simonbs/SBSAnimoji#24]
Hi, Im sorry if this has come up in the past, but when trying to build the app on my iPhone X, I get the following errors:
Code Signing Error Group
There are no accounts registered with Xcode. Add your developer account to Xcode
No profiles for 'dk.simonbs.SBSAnimoji' were found:  Xcode couldn't find any iOS App Development provisioning profiles matching 'dk.simonbs.SBSAnimoji'.
Code signing is required for product type 'Application' in SDK 'iOS 11.1'

Could anyone help me
Thanks a lot

**Comment by DavidLari** [comment]
Try this tutorial on sideloading apps: https://9to5mac.com/2016/03/27/how-to-create-free-apple-developer-account-sideload-apps/

**Comment by Archundix** [comment]
I fixed it by changing the bundle identifier to my team's name. 
Thanks a lot @simonbs @DavidLari
