### ISSUE TITLE
App not opening after a couple of days

### ISSUE THREAD

**Issue by Archundix** [simonbs/SBSAnimoji#25]
It has happened twice already, after a couple of days using the app, it suddenly crashes everytime I try to open it, having to erase and reinstall. Is there a way to fix this?
Thanks!

**Comment by migatxu** [comment]
Sideload it again. It worked for me after 11.2.1 update

**Comment by Archundix** [comment]
Ok. I’ll sideload it again and get back to comment
Thanks a lot

**Comment by Archundix** [comment]
Still, after a couple of days, the app crashes when trying to open

**Comment by DavidLari** [comment]
If you don't have a paid Apple Developer account, the app is only provisioned to run a few days before it expires. You will have to continually reinstall every few days.

**Comment by Archundix** [comment]
Crap! Thanks a lot for the heads up
