### ISSUE TITLE
Swift version?

### ISSUE THREAD

**Issue by chaitanya-ramji** [simonbs/SBSAnimoji#3]
Is there a swift version of the code? Or is someone willing to collaborate to make a swift version of the code?

**Comment by simonbs** [comment]
There's currently no Swift version of the code. I wrote the app in Objective-C because the Objective-C runtime library provides some useful functions for exploring private API. It should be possible to translate the app into Swift and pull requests for this are welcome.

**Comment by efremidze** [comment]
You can write it in swift too. Ill make a swift version.

**Comment by efremidze** [comment]
Swift Version: https://github.com/efremidze/Animoji
