### ISSUE TITLE
How do we download this?

### ISSUE THREAD

**Issue by fmanshaii** [simonbs/SBSAnimoji#5]
I am extremely interested in this code and would like to download it to my iPhone X. How would I be able to download it? Which items do I download? Do I install it as a profile? Please let me know. Thank you.

**Comment by simonbs** [comment]
@spacexdragon You will need to download the entire repository and compile the app yourself using Xcode. This requires a free developer account. 9to5mac have created a guide explaining how to create this. https://www.youtube.com/watch?v=ZvC0VWgIET4

**Comment by fmanshaii** [comment]
Thank you.
