### ISSUE TITLE
Mach-O Linker error

### ISSUE THREAD

**Issue by quangvh23** [simonbs/SBSAnimoji#6]
Undefined symbols for architecture x86_64:
  "_OBJC_METACLASS_$_AVTPuppetView", referenced from:
      _OBJC_METACLASS_$_SBSPuppetView in SBSPuppetView.o
  "_OBJC_CLASS_$_AVTPuppetView", referenced from:
      _OBJC_CLASS_$_SBSPuppetView in SBSPuppetView.o
      objc-class-ref in SBSPuppetView.o
  "_OBJC_CLASS_$_AVTPuppet", referenced from:
      objc-class-ref in MainViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I received the above error when compiling, how to link these headers to your AvatarKit.framework?

**Comment by simonbs** [comment]
@quangvh23 Are you compiling this for an iPhone X? Only supported device is iPhone X.

**Comment by ghost** [comment]
Same here, tried to build this project for Generic iOS Device.

So I assume only way to compile this code is to plug iPhone X in?

**Comment by simonbs** [comment]
@outbools Yes. The iPhone X is the only device that supports AvatarKit. https://twitter.com/stroughtonsmith/status/927852243700867073
